### ISSUE TITLE
socket error causing crash

### ISSUE THREAD

**Issue by edrex** [emersion/net-browserify#8]
While investigating #7 I am occasionally seeing the server crash:

```
eric@ark ~/S/c/n/e/connect (master)> node server.js
Server listening on port 3000
Connected to google.com:80 (ba702aedfde8c553b7704bef4a8b195c09fd0e744669625b801ed49d0f0debe7)
Forwarding socket with token ba702aedfde8c553b7704bef4a8b195c09fd0e744669625b801ed49d0f0debe7
Websocket connection closed (ba702aedfde8c553b7704bef4a8b195c09fd0e744669625b801ed49d0f0debe7)
Forwarding socket with token ba702aedfde8c553b7704bef4a8b195c09fd0e744669625b801ed49d0f0debe7
_http_outgoing.js:344
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/Users/eric/Sites/caddy.test/net-browserify/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/eric/Sites/caddy.test/net-browserify/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/Users/eric/Sites/caddy.test/net-browserify/node_modules/express/lib/response.js:249:15)
    at ServerResponse.send (/Users/eric/Sites/caddy.test/net-browserify/node_modules/express/lib/response.js:151:21)
    at Socket.<anonymous> (/Users/eric/Sites/caddy.test/net-browserify/api.js:130:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at writeAfterEnd (_stream_writable.js:161:10)
    at Socket.Writable.write (_stream_writable.js:204:5)
```

I suspect it's because two connections are open with the same token? Not sure.

**Comment by edrex** [comment]
The masked error is: `Error: write after end`
